language: node_js
sudo: false
services:
  - mongodb
node_js:
  - '4.1'
before_script:
  - 'npm install -g grunt-cli mocha'
  - cp config.json.example config.json
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
  - "export DISPLAY=:99"
after_script:
  - "./node_modules/.bin/lcov-result-merger 'coverage/**/*.info' | ./node_modules/coveralls/bin/coveralls.js"
